version: "3.4"
services:
  frontend:
    # user: 1000:1000
    container_name: front
    image: node:lts # https://nodejs.org/dist/latest-v16.x/docs/api/
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - 3000:3000
      - 127.0.0.1:8080:8080
    volumes:
      - ./frontend/:/var/www/html/app
    # command: npm run dev
    tty: true