version: "3.4"
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend 
    command: npm run dev
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./frontend/:/var/www/html/app/frontend
    tty: true