version: "3.4"
services:
  frontend:
    container_name: frontend
    image: node:lts # https://nodejs.org/dist/latest-v16.x/docs/api/
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 8000:8000
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true